name: Deploy Vercel App on Package Release

on:
  release:
    types: [published] # Déclenche seulement lors d'une release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Trigger Vite + React Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_WeQOmfSA6cMhz63H3M9kIRJPIWSx/9i5DQGcVrC" \
               -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{}'

      - name: 🚀 Trigger Next.js 15 Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_Koj6C0IolZvMbj3vmv7U8TRC7BIm/e9fHn2tSiR" \
               -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{}'

      - name: 🚀 Trigger Next.js 14 Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_Ujzcu3mC6mo742rCMw8TjMXT4yCV/uFVEAqZtbq" \
               -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{}'

      - name: 🚀 Trigger React CRA Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_jUM4KzVOBM0VmZrJ81XuWTQ4Azt9/m8cCJUb2ty" \
               -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
               -H "Content-Type: application/json" \
               --data '{}'
